### Find All Content
GET http://localhost:8084/api/content

### Get Content by ID
GET http://localhost:8084/api/content/1

### Create new Content
POST http://localhost:8084/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My second Blog",
  "description": "Hii",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-09-02T12:18:50.737662718",
  "dateUpdated": null,
  "url": ""
}

### Update existing Content/1
PUT http://localhost:8084/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "My FIRSTTT Blog",
  "description": "My FIRSTTT Blog",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-09-02T12:18:50.737662718",
  "dateUpdated": "2023-09-02T12:18:50.737662718",
  "url": "http://localhost:8080/firstBlog"
}

### Delete existing Content by ID
DELETE http://localhost:8084/api/content/2



